AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-middy-app

  Sample SAM Template for aws-sam-middy-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: products/
      Handler: app.handler
      Layers:
          - !Ref CommonLayer
      Runtime: nodejs8.10
      Events:
        Products:
          Type: Api
          Properties:
            Path: /products
            Method: get
  CommonLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: sam-app-common-layer
            Description: Dependencies and middlewares for sam app
            ContentUri: common-layer/
            CompatibleRuntimes:
              - nodejs8.10
